env:
  commonjs: true
  es6: true
  node: true
extends:
  - google
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 2018
plugins:
  - '@typescript-eslint'
  - 'prettier'
rules:
  'prettier/prettier': 2
  'no-console': 2
  'object-curly-spacing': 0
